#!/usr/bin/env bash
set -euo pipefail

# S9: weaker S7 combination to reduce over-regularization risk.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

export STEPS=400000
export CHECKPOINT_STEP=400000
export FACTOR_BATCH_RATIO=1.0
export FACTOR_ORBIT_MODE=legacy
export CROSS_NOISE_PROB="${CROSS_NOISE_PROB:-0.5}"
export FACTOR_SHARED_CONTRASTIVE_COEFF="${S9_SHARED_CONTRASTIVE_COEFF:-0.025}"
export FACTOR_SHARED_CONTRASTIVE_TEMPERATURE="${S9_SHARED_CONTRASTIVE_TEMPERATURE:-0.2}"
export FACTOR_EVOLVING_SEPARATION_COEFF="${S9_EVOLVING_SEPARATION_COEFF:-0.025}"
export FACTOR_EVOLVING_SEPARATION_MARGIN="${S9_EVOLVING_SEPARATION_MARGIN:-0.35}"
export FACTOR_SHARED_SOURCE_DEPTH="${FACTOR_SHARED_SOURCE_DEPTH:-8}"
export RUN_SUFFIX="${RUN_SUFFIX:-j50-s9-s7-contrastive-private-weak-ratio1-400k}"

run_tfcr_job s7_a5_contrastive_private
